version: 2
models:
  - name: stg_thelook__orders
    description: "Orders header; stable ids and timestamps for order activity"
    columns:
      - name: order_id
        tests: [not_null, unique]
      - name: user_id
        tests: [not_null]
      - name: order_date
        tests: [not_null]
  - name: stg_thelook__users
    description: "Users profile; canonical attributes for customers"
    columns:
      - name: user_id
        tests: [not_null, unique]
  - name: stg_thelook__products
    description: "Products catalog; category, department and distribution center key"
    columns:
      - name: product_id
        tests: [not_null, unique]
  - name: stg_thelook__order_items
    description: "Order line items; per item pricing and status"
    columns:
      - name: order_item_id
        tests: [not_null, unique]
      - name: order_id
        tests: [not_null]
      - name: user_id
        tests: [not_null]
      - name: product_id
        tests: [not_null]
  - name: stg_thelook__distribution_centers
    description: "Distribution centers; location reference"
    columns:
      - name: distribution_center_id
        tests: [not_null, unique]
