version: 2
models:
  - name: stg_thelook__orders
    description: "Cleaned orders from TheLook"
    columns:
      - name: order_id
        tests: [not_null, unique]
      - name: user_id
        tests: [not_null]
      - name: order_date
        tests: [not_null]
  - name: stg_thelook__users
    description: "Cleaned users from TheLook"
    columns:
      - name: user_id
        tests: [not_null, unique]
